insert into BUCKET (BUCKET_ID,CATEGORY_ID,BUCKET_DESCRIPTION,IS_ACTIVE,SKILL_TYPE_ID) values (1,11,'topic',1,1);
insert into BUCKET (BUCKET_ID,CATEGORY_ID,BUCKET_DESCRIPTION,IS_ACTIVE,SKILL_TYPE_ID) values (2,2,'java',0,2);
insert into BUCKET (BUCKET_ID,CATEGORY_ID,BUCKET_DESCRIPTION,IS_ACTIVE,SKILL_TYPE_ID) values (4,3,'framework',0,4);
insert into BUCKET (BUCKET_ID,CATEGORY_ID,BUCKET_DESCRIPTION,IS_ACTIVE,SKILL_TYPE_ID) values (5,4,'backend',1,5);
