insert into BUCKET (BUCKET_ID,CATEGORY_ID,BUCKET_DESCRIPTION,IS_ACTIVE,SKILL_TYPE_ID) values (1,1,'topic',1,1);
insert into BUCKET (BUCKET_ID,CATEGORY_ID,BUCKET_DESCRIPTION,IS_ACTIVE,SKILL_TYPE_ID) values (2,2,'task',0,2);
insert into BUCKET (BUCKET_ID,CATEGORY_ID,BUCKET_DESCRIPTION,IS_ACTIVE,SKILL_TYPE_ID) values (3,2,'questions',1,3);
insert into BUCKET (BUCKET_ID,CATEGORY_ID,BUCKET_DESCRIPTION,IS_ACTIVE,SKILL_TYPE_ID) values (4,3,'qc',0,4);
insert into BUCKET (BUCKET_ID,CATEGORY_ID,BUCKET_DESCRIPTION,IS_ACTIVE,SKILL_TYPE_ID) values (5,4,'panel',1,5);
