
insert into QUESTION (QUESTION_ID, BUCKET_ID, IS_ACTIVE, QUESTION_TEXT, SAMPLE_ANSWER_1, SAMPLE_ANSWER_2, SAMPLE_ANSWER_3, SAMPLE_ANSWER_4, SAMPLE_ANSWER_5) values (1001, 3, 1, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Etiam pretium iaculis justo.', 'Pellentesque at nulla.', 'Morbi porttitor lorem id ligula.', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'Suspendisse ornare consequat lectus.'); 
insert into QUESTION (QUESTION_ID, BUCKET_ID, IS_ACTIVE, QUESTION_TEXT, SAMPLE_ANSWER_1, SAMPLE_ANSWER_2, SAMPLE_ANSWER_3, SAMPLE_ANSWER_4, SAMPLE_ANSWER_5) values (1002, 1, 0, 'Duis bibendum.', 'Phasellus in felis.', 'Integer tincidunt ante vel ipsum.', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Aenean auctor gravida sem.', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.'); 
insert into QUESTION (QUESTION_ID, BUCKET_ID, IS_ACTIVE, QUESTION_TEXT, SAMPLE_ANSWER_1, SAMPLE_ANSWER_2, SAMPLE_ANSWER_3, SAMPLE_ANSWER_4, SAMPLE_ANSWER_5) values (1003, 2, 1, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.','Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',  'Vitae mattis nibh ligula nec sem.', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'In hac habitasse platea dictumst.', 'In hac habitasse platea dictumst.'); 
insert into QUESTION (QUESTION_ID, BUCKET_ID, IS_ACTIVE, QUESTION_TEXT, SAMPLE_ANSWER_1, SAMPLE_ANSWER_2, SAMPLE_ANSWER_3, SAMPLE_ANSWER_4, SAMPLE_ANSWER_5) values (1004, 3, 1, 'Fusce posuere felis sed lacus.', 'Praesent lectus.', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Sed ante.', 'Donec quis orci eget orci vehicula condimentum.', 'Aliquam sit amet diam in magna bibendum imperdiet.'); 
insert into QUESTION (QUESTION_ID, BUCKET_ID, IS_ACTIVE, QUESTION_TEXT, SAMPLE_ANSWER_1, SAMPLE_ANSWER_2, SAMPLE_ANSWER_3, SAMPLE_ANSWER_4, SAMPLE_ANSWER_5) values (1005, 4, 1, 'Nunc nisl.', 'Maecenas pulvinar lobortis est.', 'Vivamus vel nulla eget eros elementum pellentesque.', 'Donec posuere metus vitae ipsum.', 'Pellentesque eget nunc.', 'Vivamus vestibulum sagittis sapien.'); 
insert into QUESTION (QUESTION_ID, BUCKET_ID, IS_ACTIVE, QUESTION_TEXT, SAMPLE_ANSWER_1, SAMPLE_ANSWER_2, SAMPLE_ANSWER_3, SAMPLE_ANSWER_4, SAMPLE_ANSWER_5) values (1006, 1, 0, 'Etiam vel augue.', 'Nulla mollis molestie lorem.', 'Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'In sagittis dui vel nisl.', 'Nam tristique tortor eu pede.', 'Etiam faucibus cursus urna.'); 

insert into CATEGORY (CATEGORY_ID, TITLE, IS_ACTIVE) values (404, 'JAVA', 1); 
insert into CATEGORY (CATEGORY_ID, TITLE, IS_ACTIVE) values (405, 'SQL', 1);
insert into CATEGORY (CATEGORY_ID, TITLE, IS_ACTIVE) values (406, 'Hibernate', 0); 

insert into weight (weight_id, weight, skill_type_id, category_id) values (28424545, 30, 2842, 4545);
insert into weight (weight_id, weight, skill_type_id, category_id) values (28434546, 30, 2843, 4546);
insert into weight (weight_id, weight, skill_type_id, category_id) values (34826454, 30, 3482, 6454);